# Generated by Django 3.0.3 on 2020-04-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег'),
        ),
    ]
