# Generated by Django 3.0.3 on 2020-04-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200407_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='OperationType',
        ),
        migrations.AlterModelOptions(
            name='operationtype',
            options={'verbose_name': 'Вид операции', 'verbose_name_plural': 'Виды операции'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='action',
            new_name='operation_type',
        ),
    ]
