# Generated by Django 3.0.3 on 2020-04-09 13:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200407_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Сумма')),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 9, 13, 25, 18, 322510, tzinfo=utc), verbose_name='Месяц бюджета')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
