# Generated by Django 3.0.3 on 2020-04-14 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plannedbudget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedbudget',
            options={'verbose_name': 'Планируемый бюджет', 'verbose_name_plural': 'Планируемые бюджеты'},
        ),
        migrations.AlterField(
            model_name='plannedbudget',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 14, 13, 44, 9, 965511, tzinfo=utc), verbose_name='Месяц бюджета'),
        ),
    ]
