# Generated by Django 3.0.3 on 2020-06-06 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_authcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('cash', 'наличные'), ('non_cash', 'безналичные')], default='cash', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 9, 18, 19, 294828, tzinfo=utc), verbose_name='Дата окончания действия'),
        ),
    ]
