# Generated by Django 3.0.3 on 2020-06-10 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200606_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 10, 26, 15, 387309, tzinfo=utc), verbose_name='Дата окончания действия'),
        ),
    ]
