# Generated by Django 3.0.3 on 2020-06-11 06:39

import budget_controller.utils.date_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200610_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authcode',
            options={'ordering': ['-id'], 'verbose_name': 'Код', 'verbose_name_plural': 'Коды'},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-id'], 'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='operationtype',
            options={'ordering': ['-id'], 'verbose_name': 'Вид операции', 'verbose_name_plural': 'Виды операции'},
        ),
        migrations.AlterModelOptions(
            name='plannedbudget',
            options={'ordering': ['-id'], 'verbose_name': 'Планируемый бюджет', 'verbose_name_plural': 'Планируемые бюджеты'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterField(
            model_name='authcode',
            name='end_date',
            field=models.DateTimeField(default=budget_controller.utils.date_utils.increase_datetime_now_for_10_minutes, verbose_name='Дата окончания действия'),
        ),
    ]
